/**
 * InsightsList — Container for AI-generated carbon reduction insights.
 *
 * Accessibility features:
 *   - <section aria-labelledby="insights-heading" aria-live="polite">
 *   - <ol aria-label="Personalized carbon reduction insights">
 *   - Gemini badge uses aria-label to explain the source
 *   - Total saving is announced via aria-live
 */

import { useState } from 'react';
import type { InsightsResponse } from '../../types';
import { formatKg } from '../../utils/formatters';
import { InsightCard } from './InsightCard';
import { useCarbonStore } from '../../store/carbonStore';

interface InsightsListProps {
  insightsResponse: InsightsResponse;
}

export const InsightsList = ({ insightsResponse }: InsightsListProps) => {
  const { insights, source, total_potential_saving_kg } = insightsResponse;
  const saveEntry = useCarbonStore(s => s.saveEntry);
  const result = useCarbonStore(s => s.result);
  const committedActions = useCarbonStore(s => s.committedActions);
  const commitAction = useCarbonStore(s => s.commitAction);
  const uncommitAction = useCarbonStore(s => s.uncommitAction);
  const [isSaved, setIsSaved] = useState(false);

  const currentTotal = result ? result.total_kg : 0;
  
  // Calculate active savings based on ticked commitments
  const committedSaving = insights.reduce((acc, curr) => {
    const isCommitted = committedActions.some(a => a.action === curr.action);
    return acc + (isCommitted ? curr.estimated_saving_kg : 0);
  }, 0);

  const projectedTotal = Math.max(0, currentTotal - committedSaving);
  const reductionPercentage = currentTotal > 0 ? (committedSaving / currentTotal) * 100 : 0;

  const handleSave = async () => {
    await saveEntry();
    setIsSaved(true);
    setTimeout(() => setIsSaved(false), 3000);
  };

  return (
    <section
      aria-labelledby="insights-heading"
      aria-live="polite"
      aria-atomic="false"
      className="space-y-6 animate-slide-up"
    >
      {/* Reduction Plan Header */}
      <div className="bg-white/80 dark:bg-slate-900/60 backdrop-blur-md rounded-2xl shadow-sm border border-gray-200/50 dark:border-slate-800/40 p-6 space-y-5">
        <div className="flex items-start justify-between flex-wrap gap-3">
          <div>
            <h2 id="insights-heading" className="text-xl font-bold text-gray-900 dark:text-white mb-1">
              Your Personalised Reduction Plan
            </h2>
            <p className="text-sm text-gray-500 dark:text-slate-400">
              Targeting your top emission sources with specific, actionable guidelines.
            </p>
          </div>
          {source === 'gemini' && (
            <span
              aria-label="Insights powered by Google Gemini AI"
              className="
                inline-flex items-center gap-1.5 text-xs font-bold
                bg-gradient-to-r from-blue-50 to-primary-50
                dark:from-blue-950/20 dark:to-primary-950/25
                text-primary-700 dark:text-primary-400 border border-primary-200/60 dark:border-primary-900/50
                px-3 py-1.5 rounded-full shadow-sm ai-glow
              "
            >
              <span aria-hidden="true" className="animate-spin-slow">✨</span>
              Powered by Google Gemini AI
            </span>
          )}
          {source === 'rules' && (
            <span
              aria-label="Insights generated by rule-based engine (Gemini AI unavailable)"
              className="
                inline-flex items-center gap-1.5 text-xs font-semibold
                bg-gray-55 text-gray-500 border border-gray-200
                dark:bg-slate-800 dark:text-slate-450 dark:border-slate-700
                px-3 py-1.5 rounded-full
              "
            >
              <span aria-hidden="true">🔧</span>
              Rule-based insights
            </span>
          )}
        </div>

        {/* Dynamic commitments dashboard */}
        <div className="p-5 bg-gradient-to-br from-primary-500/10 via-teal-500/5 to-transparent dark:from-primary-500/5 dark:via-teal-500/3 dark:to-transparent rounded-2xl border border-primary-100/50 dark:border-primary-900/20 space-y-4">
          <h3 className="text-sm font-bold text-primary-800 dark:text-primary-300 uppercase tracking-wider">
            Commitment Dashboard
          </h3>
          
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-center">
            {/* Current */}
            <div className="bg-white/60 dark:bg-slate-900/40 p-3.5 rounded-xl border border-gray-150 dark:border-slate-800/80">
              <span className="block text-xs font-bold text-gray-400 dark:text-slate-500 uppercase">Current Footprint</span>
              <span className="text-xl font-black text-gray-800 dark:text-slate-200 tabular-nums">
                {formatKg(currentTotal)}
              </span>
            </div>

            {/* Projected */}
            <div className="bg-white/60 dark:bg-slate-900/40 p-3.5 rounded-xl border border-gray-150 dark:border-slate-800/80">
              <span className="block text-xs font-bold text-gray-400 dark:text-slate-500 uppercase">Projected Footprint</span>
              <span className="text-xl font-black text-primary-600 dark:text-primary-400 tabular-nums">
                {formatKg(projectedTotal)}
              </span>
            </div>

            {/* Reduction */}
            <div className="bg-white/60 dark:bg-slate-900/40 p-3.5 rounded-xl border border-gray-150 dark:border-slate-800/80">
              <span className="block text-xs font-bold text-gray-400 dark:text-slate-500 uppercase">Impact Achieved</span>
              <span className="text-xl font-black text-emerald-600 dark:text-emerald-400 tabular-nums">
                -{reductionPercentage.toFixed(0)}%
              </span>
            </div>
          </div>

          {/* Interactive slider tracking reductions */}
          <div className="space-y-1.5">
            <div className="flex justify-between text-xs font-bold text-gray-500 dark:text-slate-400">
              <span>Goal: Paris 1.5°C Limit ({formatKg(2000)})</span>
              <span>
                {projectedTotal <= 2000 ? (
                  <span className="text-emerald-600 dark:text-emerald-400">✓ Target Aligned!</span>
                ) : (
                  <span>Need to reduce {formatKg(projectedTotal - 2000)} more</span>
                )}
              </span>
            </div>
            <div className="relative w-full h-3 bg-gray-200/70 dark:bg-slate-800 rounded-full overflow-hidden">
              <div 
                className="h-full bg-emerald-500 dark:bg-emerald-400 rounded-full transition-all duration-500"
                style={{ width: `${Math.min(100, (2000 / projectedTotal) * 100)}%` }}
              />
            </div>
          </div>
        </div>

        {/* Max Potential saving description */}
        <div className="pt-2 flex items-center justify-between gap-3 text-xs border-t border-gray-100 dark:border-slate-800/60 text-gray-500 dark:text-slate-400 font-medium">
          <span>Max Potential Savings: <strong>{formatKg(total_potential_saving_kg)}/year</strong></span>
          <span>Click cards to commit and track your live impact projection.</span>
        </div>
      </div>

      {/* Insights list */}
      <ol
        aria-label="Personalized carbon reduction insights, ordered by priority"
        className="space-y-4 list-none m-0 p-0"
      >
        {insights.map((insight, i) => {
          const isCommitted = committedActions.some(a => a.action === insight.action);
          return (
            <li key={i}>
              <InsightCard 
                insight={insight} 
                index={i} 
                committed={isCommitted}
                onToggle={() => {
                  if (isCommitted) {
                    uncommitAction(insight.action);
                  } else {
                    commitAction(insight);
                  }
                }}
              />
            </li>
          );
        })}
      </ol>

      {/* Save button */}
      <div className="flex justify-center pt-2">
        <button
          onClick={handleSave}
          disabled={isSaved}
          className={`
            flex items-center gap-2 text-sm font-semibold
            px-6 py-3 rounded-xl border transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 dark:focus-visible:ring-offset-slate-950 active:scale-95
            ${
              isSaved
                ? 'bg-emerald-50 border-emerald-300 text-emerald-700 dark:bg-emerald-950/20 dark:border-emerald-900/60 dark:text-emerald-400'
                : 'bg-white hover:bg-gray-50 dark:bg-slate-900 dark:hover:bg-slate-800 text-gray-700 dark:text-slate-200 border-gray-300 dark:border-slate-700 hover:border-gray-400 dark:hover:border-slate-600'
            }
          `}
          aria-label="Save this carbon footprint snapshot to your history"
        >
          <span>{isSaved ? '✓ Saved' : '💾 Save to History'}</span>
        </button>
      </div>
    </section>
  );
};
